export const CHANGE_FIlTER = 'CHANGE_FIlTER';
export const CHANGE_TABS = 'CHANGE_TABS';
export const CHANGE_SEARCHID = 'CHANGE_SEARCHID';
export const CHANGE_TICKETS = 'CHANGE_TICKETS';
export const CHANGE_ACTIVE_TICKETS = 'CHANGE_ACTIVE_TICKETS';
export const ADD_TICKETS = 'ADD_TICKETS';